spring.application.name=moki_market_backend

server.servlet.context-path=/v1/api

spring.datasource.url=jdbc:postgresql://localhost:15432/moki_db
spring.datasource.username=username
spring.datasource.password=password

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

springdoc.api-docs.version=openapi_3_0

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=none

spring.data.web.pageable.serialization-mode=via-dto

spring.jpa.properties.hibernate.default_batch_fetch_size=100

spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

s3.url=http://localhost:9000
s3.accessKey=minioadmin
s3.secretKey=minioadmin
s3.bucket=moki-images
s3.region=us-east-1

minio.external-url=http://localhost:9000/moki-images/

cors.allowed-origins=http://localhost:3000,http://localhost:5173,https://moki.com.ua

jwt.refresh-secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

jwt.access.ttl=10m
jwt.refresh.ttl=2d

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=moki.mrkt@gmail.com
spring.mail.password=txql ouct ujer qils

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

bot.name=MokiSystemBot
bot.key=8467866406:AAF4QED68igEop2G2qBin0fhqrWdZ6m0KpE
bot.chat.id=-5289181736

management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
